FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set strict-ssl false
RUN npm config set registry http://registry.npmjs.org/
RUN npm config delete proxy
RUN npm config delete https-proxy

RUN npm install

COPY prisma ./prisma
RUN cp prisma/schema.postgres.prisma prisma/schema.prisma
RUN npx prisma generate

COPY scripts ./scripts
RUN chmod +x scripts/docker-entrypoint.sh

COPY . .

EXPOSE 3001

CMD ["sh", "scripts/docker-entrypoint.sh"]
